# Generated by Django 5.0.2 on 2024-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.CharField(max_length=100)),
                ('s_ids', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('spass', models.CharField(max_length=100)),
            ],
        ),
    ]
