# Generated by Django 3.1.1 on 2020-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.CharField(max_length=100)),
                ('s_ids', models.CharField(max_length=1000)),
            ],
        ),
    ]
